import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQuery from "@/components/ReactQuery";
import { Toaster } from "react-hot-toast";
import { ReactNode } from "react";
import { Session } from "next-auth";
import NextAuthProvider from "@/components/NextAuthProvider";
import { SocketProvider } from "@/components/socketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en">
      <body className={inter.className } style={{backgroundColor: '#fafafa'}}>
        <NextAuthProvider session={session}>
          <SocketProvider>
            <ReactQuery>
              <Toaster position="top-center" reverseOrder={false} />
              {children}
            </ReactQuery>
          </SocketProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
